### PR TITLE
Fix discrepancy in Board/PremiumSquares, add test case for consistency

### PR DESCRIPTION
**Pull request by epkanol**
Merry X-mas, Emily!
I noticed a discrepancy between the Board and PremiumSquares while doing the kata today.
Checked the wikipedia page for reference on the correct board design, and updated the Board accordingly.
Also made a unit test, to sync changes to the json in the root dir

Note, I have NOT checked the csharp code, as I don't have that environment.
But writing a similar unit test for csharp (this time verifying from json to csharp) should be a no-brainer, for someone having the C# env up and running.

Thanks for the fun kata, I'll see if I can play around with it with some subjects

### CODE REVIEW

**Comment by epkanol** [comment]
I'm still learning the github WoW, thought I could create a new PR, but it appears as if my two commits now are combined.
Anyway, whenever I teach solution design to people, I think it could be useful to surprise them a little.
So, my thoughts with the second commit is to add another set of rules, with some differences from "plain Scrabble" (these rules come from "Barnens Alfapet", a game by Alga):
* all letters are now worth 1 point, letters also include Å Ä and Ö
* Some tiles are worth additional 1, 2, 3 or 4 points, thus no multiplication any more
* There are no word bonus
* The board is now 17x17 slots, instead of original 15x15, with different pattern

The idea is to first let people solve the first, original Scrabble kata, and then show them the second set of rules.
A "good solution" would have encapsulated the original rules, which would allow us to solve the new rule set with minimal changes to the existing score calculator (SOLID architecture)
The point of adding the additional rules are meant to underscore that.

WDYT? Is it a worthwhile addition? I don't really know if the new rule set belongs in the master branch, or in a totally different branch/repo/whatever. Point is, I would like pupils to first do the original kata, then solve the new requirements in a clean way. Kind of like real life experiences :-)
Best wishes,
/Anders

**Comment by codecop** [comment]
Sorry for not seeing this for 5 years. I cannot merge the tests, as these are part of the exercise. The fix in the data might be useful and could be added to the other languages easily. What do you think @emilybache ? Do you care for the  reference on the correct board design according to Wikipedia? It could confuse people if it differs, but maybe it does not matter?

**Comment by epkanol** [comment]
Thanks for reminding me, Peter :)

I wrote the unit tests just to be safe that I was doing the right thing (like I always do in small projects like this)
I don't know if the changed requirements should be part of this kata, or of another one entirely.
But I kinda like to show that life is full of surprises (that's why it's important to keep the "soft" in software...)

Take care, and thanks for picking this up!
Anders

**Comment by emilybache** [comment]
Actually I think these tests for consistency are a good addition and don't take away from the exercise. Thanks for the additional board and rules, I like the way you're thinking. I'm sorry it took me so long to react to your PR.

**Comment by codecop** [comment]
Should we also update the data of the ported languages? That would be possible even without the environments as it replaces just fields in array? @epkanol

**Comment by emilybache** [comment]
That is a good idea

**Pull request merged**
