### PR TITLE
Add Python version

### PR DESCRIPTION
**Pull request by Chris-May**
Adds a Python version with pytest

### CODE REVIEW

**Comment by codecop** [comment]
Thank you. Could you also add a ScrableDataTest as in the Java version please? See https://github.com/emilybache/Scrabble-Kata/blob/master/java/src/test/java/codingdojo/ScrabbleDataTest.java

**Comment by Chris-May** [comment]
Oh! Absolutely! I somehow missed those. Sorry about that @codecop.
I also added some pytest configuration to hopefully prevent any kind of import or test-finding issues.

**Comment by codecop** [comment]
Thank you looks good. Vote to merge @emilybache

**Comment by emilybache** [comment]
Thankyou!

**Pull request merged**
